baseURL = "https://investingwithmyfeet.com/"
# Make links relative, so they still work if baseURL isn't perfect
relativeURLs = true
languageCode = 'en-us'
title = 'Investing with My Feet Journey'
theme = 'PaperMod'

[pagination]
  pagerSize = 10
  
# Silence warnings if you don't use tags/categories yet
disableKinds = ["taxonomy", "term"]

[params]
  defaultTheme = "auto"

[params.homeInfoParams]
  Title = 'Facts and Hacks for Begginer Investors'
  Content = "Not just investing, value creation foundations"

[menu]

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Dictionary"
  url = "/dictionary/"
  weight = 2

[[menu.main]]
  name = "Dashboard"
  url = "https://app.investwithalan.ai"
  weight = 3

  